credentials:
  users:
    guest:
      roles: [ super ]

iproto:
  listen:
    - uri: localhost:3301

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          master: { }
