core/tarantool.o: CFLAGS += -DSTORAGE

obj += core/admin.o
obj += mod/silverbox/box.o
obj += mod/silverbox/index.o
obj += mod/silverbox/memcached.o
obj += third_party/qsort_arg.o

cfg_tmpl += mod/silverbox/box_cfg.cfg_tmpl
