/* Automatically generated.  Do not edit */
/* See the tool/mkopcodec.tcl script for details. */
#include "sqliteInt.h"
#if !defined(SQLITE_OMIT_EXPLAIN) \
 || defined(VDBE_PROFILE) \
 || defined(SQLITE_DEBUG)
#if defined(SQLITE_ENABLE_EXPLAIN_COMMENTS) || defined(SQLITE_DEBUG)
# define OpHelp(X) "\0" X
#else
# define OpHelp(X)
#endif
const char *sqlite3OpcodeName(int i){
 static const char *const azName[] = {
    /*   0 */ "Savepoint"        OpHelp(""),
    /*   1 */ "AutoCommit"       OpHelp(""),
    /*   2 */ "Transaction"      OpHelp(""),
    /*   3 */ "SorterNext"       OpHelp(""),
    /*   4 */ "PrevIfOpen"       OpHelp(""),
    /*   5 */ "Or"               OpHelp("r[P3]=(r[P1] || r[P2])"),
    /*   6 */ "And"              OpHelp("r[P3]=(r[P1] && r[P2])"),
    /*   7 */ "Not"              OpHelp("r[P2]= !r[P1]"),
    /*   8 */ "NextIfOpen"       OpHelp(""),
    /*   9 */ "Prev"             OpHelp(""),
    /*  10 */ "Next"             OpHelp(""),
    /*  11 */ "Checkpoint"       OpHelp(""),
    /*  12 */ "JournalMode"      OpHelp(""),
    /*  13 */ "IsNull"           OpHelp("if r[P1]==NULL goto P2"),
    /*  14 */ "NotNull"          OpHelp("if r[P1]!=NULL goto P2"),
    /*  15 */ "Ne"               OpHelp("IF r[P3]!=r[P1]"),
    /*  16 */ "Eq"               OpHelp("IF r[P3]==r[P1]"),
    /*  17 */ "Gt"               OpHelp("IF r[P3]>r[P1]"),
    /*  18 */ "Le"               OpHelp("IF r[P3]<=r[P1]"),
    /*  19 */ "Lt"               OpHelp("IF r[P3]<r[P1]"),
    /*  20 */ "Ge"               OpHelp("IF r[P3]>=r[P1]"),
    /*  21 */ "ElseNotEq"        OpHelp(""),
    /*  22 */ "BitAnd"           OpHelp("r[P3]=r[P1]&r[P2]"),
    /*  23 */ "BitOr"            OpHelp("r[P3]=r[P1]|r[P2]"),
    /*  24 */ "ShiftLeft"        OpHelp("r[P3]=r[P2]<<r[P1]"),
    /*  25 */ "ShiftRight"       OpHelp("r[P3]=r[P2]>>r[P1]"),
    /*  26 */ "Add"              OpHelp("r[P3]=r[P1]+r[P2]"),
    /*  27 */ "Subtract"         OpHelp("r[P3]=r[P2]-r[P1]"),
    /*  28 */ "Multiply"         OpHelp("r[P3]=r[P1]*r[P2]"),
    /*  29 */ "Divide"           OpHelp("r[P3]=r[P2]/r[P1]"),
    /*  30 */ "Remainder"        OpHelp("r[P3]=r[P2]%r[P1]"),
    /*  31 */ "Concat"           OpHelp("r[P3]=r[P2]+r[P1]"),
    /*  32 */ "Goto"             OpHelp(""),
    /*  33 */ "BitNot"           OpHelp("r[P1]= ~r[P1]"),
    /*  34 */ "Gosub"            OpHelp(""),
    /*  35 */ "InitCoroutine"    OpHelp(""),
    /*  36 */ "Yield"            OpHelp(""),
    /*  37 */ "MustBeInt"        OpHelp(""),
    /*  38 */ "Jump"             OpHelp(""),
    /*  39 */ "Once"             OpHelp(""),
    /*  40 */ "If"               OpHelp(""),
    /*  41 */ "IfNot"            OpHelp(""),
    /*  42 */ "SeekLT"           OpHelp("key=r[P3@P4]"),
    /*  43 */ "SeekLE"           OpHelp("key=r[P3@P4]"),
    /*  44 */ "SeekGE"           OpHelp("key=r[P3@P4]"),
    /*  45 */ "SeekGT"           OpHelp("key=r[P3@P4]"),
    /*  46 */ "NoConflict"       OpHelp("key=r[P3@P4]"),
    /*  47 */ "NotFound"         OpHelp("key=r[P3@P4]"),
    /*  48 */ "Found"            OpHelp("key=r[P3@P4]"),
    /*  49 */ "Last"             OpHelp(""),
    /*  50 */ "SorterSort"       OpHelp(""),
    /*  51 */ "Sort"             OpHelp(""),
    /*  52 */ "Rewind"           OpHelp(""),
    /*  53 */ "IdxLE"            OpHelp("key=r[P3@P4]"),
    /*  54 */ "IdxGT"            OpHelp("key=r[P3@P4]"),
    /*  55 */ "IdxLT"            OpHelp("key=r[P3@P4]"),
    /*  56 */ "IdxGE"            OpHelp("key=r[P3@P4]"),
    /*  57 */ "Program"          OpHelp(""),
    /*  58 */ "FkIfZero"         OpHelp("if fkctr[P1]==0 goto P2"),
    /*  59 */ "IfPos"            OpHelp("if r[P1]>0 then r[P1]-=P3, goto P2"),
    /*  60 */ "IfNotZero"        OpHelp("if r[P1]!=0 then r[P1]--, goto P2"),
    /*  61 */ "DecrJumpZero"     OpHelp("if (--r[P1])==0 goto P2"),
    /*  62 */ "Init"             OpHelp("Start at P2"),
    /*  63 */ "Return"           OpHelp(""),
    /*  64 */ "EndCoroutine"     OpHelp(""),
    /*  65 */ "HaltIfNull"       OpHelp("if r[P3]=null halt"),
    /*  66 */ "Halt"             OpHelp(""),
    /*  67 */ "Integer"          OpHelp("r[P2]=P1"),
    /*  68 */ "Bool"             OpHelp("r[P2]=P1"),
    /*  69 */ "Int64"            OpHelp("r[P2]=P4"),
    /*  70 */ "String"           OpHelp("r[P2]='P4' (len=P1)"),
    /*  71 */ "Null"             OpHelp("r[P2..P3]=NULL"),
    /*  72 */ "SoftNull"         OpHelp("r[P1]=NULL"),
    /*  73 */ "Blob"             OpHelp("r[P2]=P4 (len=P1, subtype=P3)"),
    /*  74 */ "Variable"         OpHelp("r[P2]=parameter(P1,P4)"),
    /*  75 */ "String8"          OpHelp("r[P2]='P4'"),
    /*  76 */ "Move"             OpHelp("r[P2@P3]=r[P1@P3]"),
    /*  77 */ "Copy"             OpHelp("r[P2@P3+1]=r[P1@P3+1]"),
    /*  78 */ "SCopy"            OpHelp("r[P2]=r[P1]"),
    /*  79 */ "IntCopy"          OpHelp("r[P2]=r[P1]"),
    /*  80 */ "ResultRow"        OpHelp("output=r[P1@P2]"),
    /*  81 */ "CollSeq"          OpHelp(""),
    /*  82 */ "Function0"        OpHelp("r[P3]=func(r[P2@P5])"),
    /*  83 */ "Function"         OpHelp("r[P3]=func(r[P2@P5])"),
    /*  84 */ "AddImm"           OpHelp("r[P1]=r[P1]+P2"),
    /*  85 */ "RealAffinity"     OpHelp(""),
    /*  86 */ "Cast"             OpHelp("affinity(r[P1])"),
    /*  87 */ "Permutation"      OpHelp(""),
    /*  88 */ "Compare"          OpHelp("r[P1@P3] <-> r[P2@P3]"),
    /*  89 */ "Column"           OpHelp("r[P3]=PX"),
    /*  90 */ "Affinity"         OpHelp("affinity(r[P1@P2])"),
    /*  91 */ "MakeRecord"       OpHelp("r[P3]=mkrec(r[P1@P2])"),
    /*  92 */ "Count"            OpHelp("r[P2]=count()"),
    /*  93 */ "FkCheckCommit"    OpHelp(""),
    /*  94 */ "TTransaction"     OpHelp(""),
    /*  95 */ "ReadCookie"       OpHelp(""),
    /*  96 */ "SetCookie"        OpHelp(""),
    /*  97 */ "ReopenIdx"        OpHelp("root=P2"),
    /*  98 */ "OpenRead"         OpHelp("root=P2"),
    /*  99 */ "OpenWrite"        OpHelp("root=P2"),
    /* 100 */ "OpenTEphemeral"   OpHelp("nColumn = P2"),
    /* 101 */ "SorterOpen"       OpHelp(""),
    /* 102 */ "SequenceTest"     OpHelp("if (cursor[P1].ctr++) pc = P2"),
    /* 103 */ "OpenPseudo"       OpHelp("P3 columns in r[P2]"),
    /* 104 */ "Close"            OpHelp(""),
    /* 105 */ "ColumnsUsed"      OpHelp(""),
    /* 106 */ "Sequence"         OpHelp("r[P2]=cursor[P1].ctr++"),
    /* 107 */ "NextId"           OpHelp("r[P3]=get_max(space_index[P1]{Column[P2]})"),
    /* 108 */ "NextIdEphemeral"  OpHelp("r[P3]=get_max(space_index[P1]{Column[P2]})"),
    /* 109 */ "FCopy"            OpHelp("reg[P2@cur_frame]= reg[P1@root_frame(OPFLAG_SAME_FRAME)]"),
    /* 110 */ "Delete"           OpHelp(""),
    /* 111 */ "ResetCount"       OpHelp(""),
    /* 112 */ "SorterCompare"    OpHelp("if key(P1)!=trim(r[P3],P4) goto P2"),
    /* 113 */ "SorterData"       OpHelp("r[P2]=data"),
    /* 114 */ "RowData"          OpHelp("r[P2]=data"),
    /* 115 */ "Real"             OpHelp("r[P2]=P4"),
    /* 116 */ "NullRow"          OpHelp(""),
    /* 117 */ "SorterInsert"     OpHelp("key=r[P2]"),
    /* 118 */ "IdxReplace"       OpHelp("key=r[P2]"),
    /* 119 */ "IdxInsert"        OpHelp("key=r[P2]"),
    /* 120 */ "IdxDelete"        OpHelp("key=r[P2@P3]"),
    /* 121 */ "Destroy"          OpHelp(""),
    /* 122 */ "Clear"            OpHelp(""),
    /* 123 */ "ResetSorter"      OpHelp(""),
    /* 124 */ "ParseSchema2"     OpHelp("rows=r[P1@P2]"),
    /* 125 */ "ParseSchema3"     OpHelp("name=r[P1] sql=r[P1+1]"),
    /* 126 */ "RenameTable"      OpHelp("P1 = root, P4 = name"),
    /* 127 */ "LoadAnalysis"     OpHelp(""),
    /* 128 */ "DropTable"        OpHelp(""),
    /* 129 */ "DropIndex"        OpHelp(""),
    /* 130 */ "DropTrigger"      OpHelp(""),
    /* 131 */ "Param"            OpHelp(""),
    /* 132 */ "FkCounter"        OpHelp("fkctr[P1]+=P2"),
    /* 133 */ "MemMax"           OpHelp("r[P1]=max(r[P1],r[P2])"),
    /* 134 */ "OffsetLimit"      OpHelp("if r[P1]>0 then r[P2]=r[P1]+max(0,r[P3]) else r[P2]=(-1)"),
    /* 135 */ "AggStep0"         OpHelp("accum=r[P3] step(r[P2@P5])"),
    /* 136 */ "AggStep"          OpHelp("accum=r[P3] step(r[P2@P5])"),
    /* 137 */ "AggFinal"         OpHelp("accum=r[P1] N=P2"),
    /* 138 */ "Expire"           OpHelp(""),
    /* 139 */ "IncMaxid"         OpHelp(""),
    /* 140 */ "Noop"             OpHelp(""),
    /* 141 */ "Explain"          OpHelp(""),
  };
  return azName[i];
}
#endif
