#define TK_SEMI                             1
#define TK_EXPLAIN                          2
#define TK_QUERY                            3
#define TK_PLAN                             4
#define TK_OR                               5
#define TK_AND                              6
#define TK_NOT                              7
#define TK_IS                               8
#define TK_MATCH                            9
#define TK_LIKE_KW                         10
#define TK_BETWEEN                         11
#define TK_IN                              12
#define TK_ISNULL                          13
#define TK_NOTNULL                         14
#define TK_NE                              15
#define TK_EQ                              16
#define TK_GT                              17
#define TK_LE                              18
#define TK_LT                              19
#define TK_GE                              20
#define TK_ESCAPE                          21
#define TK_BITAND                          22
#define TK_BITOR                           23
#define TK_LSHIFT                          24
#define TK_RSHIFT                          25
#define TK_PLUS                            26
#define TK_MINUS                           27
#define TK_STAR                            28
#define TK_SLASH                           29
#define TK_REM                             30
#define TK_CONCAT                          31
#define TK_COLLATE                         32
#define TK_BITNOT                          33
#define TK_BEGIN                           34
#define TK_TRANSACTION                     35
#define TK_DEFERRED                        36
#define TK_IMMEDIATE                       37
#define TK_EXCLUSIVE                       38
#define TK_COMMIT                          39
#define TK_END                             40
#define TK_ROLLBACK                        41
#define TK_SAVEPOINT                       42
#define TK_RELEASE                         43
#define TK_TO                              44
#define TK_TABLE                           45
#define TK_CREATE                          46
#define TK_IF                              47
#define TK_EXISTS                          48
#define TK_LP                              49
#define TK_RP                              50
#define TK_AS                              51
#define TK_WITHOUT                         52
#define TK_COMMA                           53
#define TK_ID                              54
#define TK_INDEXED                         55
#define TK_ABORT                           56
#define TK_ACTION                          57
#define TK_AFTER                           58
#define TK_ANALYZE                         59
#define TK_ASC                             60
#define TK_ATTACH                          61
#define TK_BEFORE                          62
#define TK_BY                              63
#define TK_CASCADE                         64
#define TK_CAST                            65
#define TK_COLUMNKW                        66
#define TK_CONFLICT                        67
#define TK_DATABASE                        68
#define TK_DESC                            69
#define TK_DETACH                          70
#define TK_EACH                            71
#define TK_FAIL                            72
#define TK_FOR                             73
#define TK_IGNORE                          74
#define TK_INITIALLY                       75
#define TK_INSTEAD                         76
#define TK_NO                              77
#define TK_KEY                             78
#define TK_OF                              79
#define TK_OFFSET                          80
#define TK_PRAGMA                          81
#define TK_RAISE                           82
#define TK_RECURSIVE                       83
#define TK_REPLACE                         84
#define TK_RESTRICT                        85
#define TK_ROW                             86
#define TK_TRIGGER                         87
#define TK_VIEW                            88
#define TK_VIRTUAL                         89
#define TK_WITH                            90
#define TK_REINDEX                         91
#define TK_RENAME                          92
#define TK_CTIME_KW                        93
#define TK_ANY                             94
#define TK_STRING                          95
#define TK_JOIN_KW                         96
#define TK_CONSTRAINT                      97
#define TK_DEFAULT                         98
#define TK_NULL                            99
#define TK_PRIMARY                        100
#define TK_UNIQUE                         101
#define TK_CHECK                          102
#define TK_REFERENCES                     103
#define TK_AUTOINCR                       104
#define TK_ON                             105
#define TK_INSERT                         106
#define TK_DELETE                         107
#define TK_UPDATE                         108
#define TK_SET                            109
#define TK_DEFERRABLE                     110
#define TK_FOREIGN                        111
#define TK_DROP                           112
#define TK_UNION                          113
#define TK_ALL                            114
#define TK_EXCEPT                         115
#define TK_INTERSECT                      116
#define TK_SELECT                         117
#define TK_VALUES                         118
#define TK_DISTINCT                       119
#define TK_DOT                            120
#define TK_FROM                           121
#define TK_JOIN                           122
#define TK_USING                          123
#define TK_ORDER                          124
#define TK_GROUP                          125
#define TK_HAVING                         126
#define TK_LIMIT                          127
#define TK_WHERE                          128
#define TK_INTO                           129
#define TK_FLOAT                          130
#define TK_BLOB                           131
#define TK_INTEGER                        132
#define TK_VARIABLE                       133
#define TK_CASE                           134
#define TK_WHEN                           135
#define TK_THEN                           136
#define TK_ELSE                           137
#define TK_INDEX                          138
#define TK_ALTER                          139
#define TK_ADD                            140
#define TK_TO_TEXT                        141
#define TK_TO_BLOB                        142
#define TK_TO_NUMERIC                     143
#define TK_TO_INT                         144
#define TK_TO_REAL                        145
#define TK_ISNOT                          146
#define TK_END_OF_FILE                    147
#define TK_UNCLOSED_STRING                148
#define TK_FUNCTION                       149
#define TK_COLUMN                         150
#define TK_AGG_FUNCTION                   151
#define TK_AGG_COLUMN                     152
#define TK_UMINUS                         153
#define TK_UPLUS                          154
#define TK_REGISTER                       155
#define TK_VECTOR                         156
#define TK_SELECT_COLUMN                  157
#define TK_ASTERISK                       158
#define TK_SPAN                           159
#define TK_SPACE                          160
#define TK_ILLEGAL                        161

/* The token codes above must all fit in 8 bits */
#define TKFLG_MASK           0xff  

/* Flags that can be added to a token code when it is not
** being stored in a u8: */
#define TKFLG_DONTFOLD       0x100  /* Omit constant folding optimizations */
