type(box.digest)

box.digest.md4_hex()
box.digest.md5_hex()
box.digest.sha_hex()
box.digest.sha1_hex()
box.digest.sha224_hex()
box.digest.sha256_hex()
box.digest.sha384_hex()
box.digest.sha512_hex()

string.len(box.digest.md4_hex())
string.len(box.digest.md5_hex())
string.len(box.digest.sha_hex())
string.len(box.digest.sha1_hex())
string.len(box.digest.sha224_hex())
string.len(box.digest.sha256_hex())
string.len(box.digest.sha384_hex())
string.len(box.digest.sha512_hex())

string.len(box.digest.md4())
string.len(box.digest.md5())
string.len(box.digest.sha())
string.len(box.digest.sha1())
string.len(box.digest.sha224())
string.len(box.digest.sha256())
string.len(box.digest.sha384())
string.len(box.digest.sha512())

box.digest.md5_hex(123)
box.digest.md5_hex('123')
box.digest.md5_hex(true)
box.digest.md5_hex('true')
box.digest.md5_hex(nil)
box.digest.md5_hex()

box.digest.crc32()
box.digest.crc32_update(4294967295, '')

box.digest.crc32('abc')
box.digest.crc32_update(4294967295, 'abc')

box.digest.crc32('abccde')
box.digest.crc32_update(box.digest.crc32('abc'), 'cde')
