box.insert(box.schema.SPACE_ID, 0, 0, 'tweedledum')
box.insert(box.schema.INDEX_ID, 0, 0, 'primary', 'hash', 1, 1, 0, 'num')

box.errinj.info()
box.errinj.set("some-injection", true)
box.errinj.set("some-injection") -- check error
box.space[0]:select(0,222444)
box.errinj.set("ERRINJ_TESTING", true)
box.space[0]:select(0,222444)
box.errinj.set("ERRINJ_TESTING", false)

-- Check how well we handle a failed log write
box.errinj.set("ERRINJ_WAL_IO", true)
box.space[0]:insert(1)
box.space[0]:select(0,1)
box.errinj.set("ERRINJ_WAL_IO", false)
box.space[0]:insert(1)
box.errinj.set("ERRINJ_WAL_IO", true)
box.space[0]:update(1, '=p', 0, 2)
box.space[0]:select(0,1)
box.space[0]:select(0,2)
box.errinj.set("ERRINJ_WAL_IO", false)
box.space[0]:truncate()

-- Check a failed log rotation
box.errinj.set("ERRINJ_WAL_ROTATE", true)
box.space[0]:insert(1)
box.space[0]:select(0,1)
box.errinj.set("ERRINJ_WAL_ROTATE", false)
box.space[0]:insert(1)
box.errinj.set("ERRINJ_WAL_ROTATE", true)
box.space[0]:update(1, '=p', 0, 2)
box.space[0]:select(0,1)
box.space[0]:select(0,2)
box.errinj.set("ERRINJ_WAL_ROTATE", false)
box.space[0]:update(1, '=p', 0, 2)
box.space[0]:select(0,1)
box.space[0]:select(0,2)
box.errinj.set("ERRINJ_WAL_ROTATE", true)
box.space[0]:truncate()
box.errinj.set("ERRINJ_WAL_ROTATE", false)
box.space[0]:truncate()

box.space[0]:drop()
-- vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4 syntax=lua
