space = box.schema.create_space('tweedledum')
space:create_index('primary', 'hash', { parts = { 0, 'num' }})

box.errinj.info()
box.errinj.set("some-injection", true)
box.errinj.set("some-injection") -- check error
space:select(0,222444)
box.errinj.set("ERRINJ_TESTING", true)
space:select(0,222444)
box.errinj.set("ERRINJ_TESTING", false)

-- Check how well we handle a failed log write
box.errinj.set("ERRINJ_WAL_IO", true)
space:insert(1)
space:select(0,1)
box.errinj.set("ERRINJ_WAL_IO", false)
space:insert(1)
box.errinj.set("ERRINJ_WAL_IO", true)
space:update(1, '=p', 0, 2)
space:select(0,1)
space:select(0,2)
box.errinj.set("ERRINJ_WAL_IO", false)
space:truncate()

-- Check a failed log rotation
box.errinj.set("ERRINJ_WAL_ROTATE", true)
space:insert(1)
space:select(0,1)
box.errinj.set("ERRINJ_WAL_ROTATE", false)
space:insert(1)
box.errinj.set("ERRINJ_WAL_ROTATE", true)
space:update(1, '=p', 0, 2)
space:select(0,1)
space:select(0,2)
box.errinj.set("ERRINJ_WAL_ROTATE", false)
space:update(1, '=p', 0, 2)
space:select(0,1)
space:select(0,2)
box.errinj.set("ERRINJ_WAL_ROTATE", true)
space:truncate()
box.errinj.set("ERRINJ_WAL_ROTATE", false)
space:truncate()

space:drop()
