#!/bin/sh
#
# This shell script scans the opcodes.h file (which is itself generated by
# another shell script) and uses the information gleaned to create the
# dispatchtable.h file.
#
# dispatchtable.h contains array of label addresses for opcodes.

set -eu  # Strict shell (w/o -x and -o pipefail)
set -f   # disable pathname expansion

printf "static void* dispatch_table[] = {"
newline="$(printf '\n')"
IFS="$newline"
while read line; do
    case "$line" in
    '#define OP_'*)
        IFS=" "
        set -- $line
        IFS="$newline"
        name="${2#_}"
        case "$name" in
        'OP_NotUsed_'*)
            printf "NULL,\n" ;;
        *)
            printf '&&Exec_%s,\n' "$name" ;;
        esac
        printf '%33s' ""
        ;;
    esac
done < "$1"
printf "};\n"
