credentials:
  users:
    replicator:
      password:
        plain: 'topsecret'
      roles: [replication]
    client:
      password:
        plain: 'secret'
      roles: [super]

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              mode: 'rw'
          instance-002: {}
          instance-003: {}
