--
-- The test measures run time of delete and range delete operations.
--

require('compat').box_error_serialize_verbose = 'new'

local clock = require('clock')
local fiber = require('fiber')
local fio = require('fio')
local benchmark = require('benchmark')

local USAGE = [[
   engine <string, 'memtx'>          - space engine to use for the test
   index_count <number, 1>           - number of indexes in the test space
   pk_aggregate_count <number, 0>    - number of aggregates in the primary
                                       index, only valid for a MemCS space
   sk_coverity <number, 1>           - number of columns covered by secondary
                                       indexes, only valid for a MemCS space
                                       (must be greater than 0 and less than
                                       or equal to field_count)
   field_count <number, 100>         - number of columns in the test space
   row_count <number, 1000000>       - number of rows in the test space
   fill_ratio <number, 1.0>          - number of non-NULL values / row_count
   layout <string, none>             - column layout option of the index
   log <string, none>                - the file to write Tarantool logs in
   no_reuse_data <boolean, false>    - do not reuse data generated by last run
   need_warmup <boolean, false>      - warm-up before each test
   benchmark_filter <string, none>   - run tests whose name matches the pattern
   benchmark_repetitions <number, 1> - run the tests that many times each
]]

local params = benchmark.argparse(arg, {
    {'engine', 'string'},
    {'index_count', 'number'},
    {'pk_aggregate_count', 'number'},
    {'sk_coverity', 'number'},
    {'field_count', 'number'},
    {'row_count', 'number'},
    {'fill_ratio', 'number'},
    {'layout', 'string'},
    {'log', 'string'},
    {'no_reuse_data', 'boolean'},
    {'need_warmup', 'boolean'},
    {'benchmark_filter', 'string'},
    {'benchmark_repetitions', 'number'},
}, USAGE)

params.engine = params.engine or 'memtx'
params.index_count = params.index_count or 1
params.field_count = params.field_count or 100
params.row_count = params.row_count or 1000 * 1000
params.fill_ratio = params.fill_ratio or 1
params.log = params.log or nil
params.no_reuse_data = params.no_reuse_data or false
params.need_warmup = params.need_warmup or false
params.benchmark_filter = params.benchmark_filter or nil
params.benchmark_repetitions = params.benchmark_repetitions or 1

if params.layout ~= nil then
    assert(params.engine == 'memcs',
           'The layout is only valid for MemCS engine.')
end

if params.sk_coverity ~= nil then
    assert(params.engine == 'memcs',
           'The sk_coverity is only valid for MemCS engine.')
    assert(params.sk_coverity > 0 and
           params.sk_coverity <= params.field_count,
           'The sk_coverity should be in range [1, field_count].')
elseif params.engine == 'memcs' then
    params.sk_coverity = 1
end

if params.pk_aggregate_count ~= nil then
    assert(params.engine == 'memcs',
           'The pk_aggregate_count is only valid for MemCS engine.')
    assert(params.pk_aggregate_count <= params.field_count,
           'The pk_aggregate_count should be in range [0, field_count].')
elseif params.engine == 'memcs' then
    params.pk_aggregate_count = 0
end

assert(params.index_count > 0,
       'At least PK must exist.')

assert(params.fill_ratio >= 0 and params.fill_ratio <= 1,
       'Fill ratio must be in the range from 0 to 1')

-- Shows a message even if --log specified.
-- Also, unlike 'print', doesn't add newline.
local function log(...)
    io.stdout:write(string.format(...))
    io.stdout:flush()
end

log("Testing with parameters:\n")
for name, value in pairs(params) do
    log("  %s: %s\n", name, value)
end

local WORK_DIR = string.format(
    'box_delete,engine=%s,index_count=%d,pk_aggregate_count=%s,' ..
    'sk_coverity=%s,field_count=%d,row_count=%d,fill_ratio=%f,layout=%s',
    params.engine, params.index_count, params.pk_aggregate_count,
    params.sk_coverity, params.field_count, params.row_count,
    params.fill_ratio, params.layout)

if params.no_reuse_data then
    fio.rmtree(WORK_DIR)
end

fio.mkdir(WORK_DIR)

box.cfg({
    work_dir = WORK_DIR,
    log = params.log,
    -- Big enough for tests, not exactly future-proof.
    memtx_memory = 4 * 1024 * 1024 * 1024,
})

benchmark.do_or_die(box.once, 'init', function()
    log('Creating the test space...\n')
    local format = {}
    table.insert(format, {'field_1', 'unsigned'})
    for i = 2, params.field_count do
        table.insert(format, {
            name = 'field_' .. i,
            type = 'unsigned',
            is_nullable = true,
            layout = params.layout
        })
    end
    local s = box.schema.space.create('test', {
        engine = params.engine,
        field_count = #format,
        format = format,
    })
    for i = 1, params.index_count do
        local aggregates = nil
        local covers = nil
        if i == 1 and params.pk_aggregate_count ~= nil then
            aggregates = {}
            for j = 1, params.pk_aggregate_count do
                table.insert(aggregates, {
                    type = 'minmax',
                    field = 'field_' .. j,
                    name = 'field_' .. j .. '_minmax'
                })
            end
        elseif i ~= 1 and params.sk_coverity ~= nil then
            covers = {}
            for j = 2, params.sk_coverity do
                table.insert(covers, 'field_' .. j)
            end
        end
        s:create_index('index_' .. i, {
            aggregates = aggregates,
            covers = covers
        })
    end

    log('Generating the test data set...\r')
    local tuple = {}
    local pct_complete = 0
    box.begin()
    for i = 1, params.row_count do
        tuple[1] = i
        for j = 2, params.field_count do
            if params.fill_ratio <= math.random() then
                tuple[j] = box.NULL
            elseif j % 2 == 1 then
                tuple[j] = i
            else
                tuple[j] = params.row_count - i + 1
            end
        end
        s:insert(tuple)
        if i % 1000 == 0 then
            box.commit()
            local pct = math.floor(100 * i / params.row_count)
            if pct ~= pct_complete then
                log('Generating the test data set: %d%% complete\r', pct)
                pct_complete = pct
            end
            box.begin()
        end
    end
    box.commit()

    log('\nWriting a snapshot...\n')
    box.snapshot()
end)

local bench = benchmark.new(params)

local function run_test(name, func)
    log('Running %s: ', name)

    if params.need_warmup then
        log('warmup... ', name)
        box.begin()
        func()
        log('rollback... ', name)
        box.rollback()
    end

    local total_real = 0
    local total_cpu = 0
    local total_deleted = 0
    for i = 1, params.benchmark_repetitions do
        log('run %d... ', i)
        local real_time_start = clock.time()
        local cpu_time_start = clock.proc()
        box.begin()
        local deleted_count = func()
        local delta_real = clock.time() - real_time_start
        local delta_cpu = clock.proc() - cpu_time_start

        log('rollback... ', i)
        box.rollback()

        total_real = total_real + delta_real
        total_cpu = total_cpu + delta_cpu
        total_deleted = total_deleted + deleted_count
    end

    bench:add_result(name, {
        real_time = total_real,
        cpu_time = total_cpu,
        items = total_deleted,
    })

    log('done.\n')
end

local tests = {
    {
        name = 'delete_all_from_first',
        func = function()
            assert(box.space.test:len() == params.row_count)
            for i = 1, params.row_count do
                box.space.test:delete({i})
            end
            assert(box.space.test:len() == 0);
            return params.row_count
        end,
    },
    {
        name = 'delete_all_from_last',
        func = function()
            assert(box.space.test:len() == params.row_count)
            for i = params.row_count, 1, -1 do
                box.space.test:delete({i})
            end
            assert(box.space.test:len() == 0);
            return params.row_count
        end,
    },
    {
        name = 'delete_range_all',
        func = function()
            assert(box.space.test:len() == params.row_count)
            box.space.test:delete_range({}, {})
            assert(box.space.test:len() == 0);
            return params.row_count
        end,
    },
    {
        name = 'delete_range_all_but_last',
        func = function()
            assert(box.space.test:len() == params.row_count)
            box.space.test:delete_range({}, {box.space.test:len()})
            assert(box.space.test:len() == 1);
            return params.row_count - 1
        end,
    },
    {
        name = 'delete_range_all_by_1000',
        func = function()
            assert(box.space.test:len() == params.row_count)
            local batch_size = 1000
            for next_1000 = batch_size + 1, params.row_count + 1, batch_size do
                box.space.test:delete_range({}, {next_1000})
            end
            assert(box.space.test:len() <= batch_size)
            box.space.test:delete_range({}, {})
            assert(box.space.test:len() == 0)
            return params.row_count
        end
    }
}

-- Just a very big value so no fiber slice exceeding happens.
fiber.set_max_slice(9000)

for _, test in ipairs(tests) do
    if params.benchmark_filter == nil or
       test.name:match(params.benchmark_filter) then
        benchmark.do_or_die(run_test, test.name, test.func)
    else
        log('Skipped %s (doesn\'t match "%s").\n',
            test.name, params.benchmark_filter)
    end
end

bench:dump_results()

os.exit(0)
