=head1 NAME

tarantool- a Lua application server and a database management system

=head1 SYNOPSIS

    tarantool script.lua [OPTIONS] [SCRIPT [ARGS]]

=head1 DESCRIPTION

Tarantool is a Lua application server fully compatible with Lua
5.1.

It includes a mature database to persist, replicate and recover application
state and a curated set of Lua modules for networking, I/O, messaging, data
formats and more.

It is designed to let developers quickly create efficient,
reliable and powerful micro-services and backend applications
for Internet.

Key features:

=over

=item *

Fully compatible with Lua 5.1.

=item *

Coroutines and asynchronous I/O to implement high-performance
lock-free access to data

=item *

ACID transactions

=item *

ANSI SQL, Lua stored procedures and triggers

=item *

Authentication and access control

=item *

Master-master replication and automatic sharding

=back

=head1 OPTIONS

All command line options are passed to the interpreted script.
When no script name is provided, the server responds to:

=over

=item -h, --help

Display helpscreen and exit.

=item -V, --version

Print program version and exit.

=item -e EXRP

Execute string 'EXPR'.

=item -l NAME

Require library 'NAME'.

=item -i

Enter interactive mode after executing 'SCRIPT'.

=item --

Stop handling options.

=item -

Execute stdin and stop handling options.

=back

=head1 SEE ALSO

tarantoolctl(1), Tarantool documentation at http://tarantool.org

=head1 COPYRIGHT

Copyright (C) 2010-2017 Tarantool AUTHORS: please see AUTHORS file.

=cut
