=head1 NAME

tarantool - a Lua application server and a database management system

=head1 SYNOPSIS

    tarantool [OPTIONS] [SCRIPT [ARGS]]

=head1 DESCRIPTION

Tarantool is a Lua application server fully compatible with Lua 5.1.

It includes a mature database to persist, replicate and recover application
state and a curated set of Lua modules for networking, I/O, messaging, data
formats and more.

It is designed to let developers quickly create efficient, reliable and
powerful micro-services and backend applications for the Internet.

Key features:

=over

=item *

Fully compatible with Lua 5.1.

=item *

Coroutines and asynchronous I/O to implement high-performance lock-free
access to data.

=item *

ACID transactions.

=item *

ANSI SQL, Lua stored procedures and triggers.

=item *

Authentication and access control.

=item *

Master-master replication and automatic sharding.

=back

=head1 OPTIONS

You can use these options before (or instead of) the interpreted 'SCRIPT'
name:

=over

=item -h, --help

Display the help screen and exit.

=item -V, -v, --version

Print the program version and exit.

=item -e EXRP

Execute the string 'EXPR'.

=item -l NAME

Require the library 'NAME'.

=item -i

Enter the interactive mode after executing 'SCRIPT'.

=item --

Stop handling options.

=item -

Execute stdin and stop handling options.

=back

=head1 SEE ALSO

tarantoolctl(1), Tarantool documentation at http://tarantool.org

=head1 COPYRIGHT

Copyright (C) 2010-2017 Tarantool AUTHORS: please see AUTHORS file.

=cut
