=head1 NAME

tarantool- a Lua application server and a NoSQL database

=head1 SYNOPSIS

    tarantool [OPTIONS]

=head1 DESCRIPTION

Tarantool is a Lua application server and a NoSQL database.

Its key properties include:

=over

=item *
    
Licence: simplified BSD

=item *
    
All data is maintained in RAM

=item *
    
Data persistence is implemented using Write Ahead Log and snapshotting

=item *
    
Supports asynchronous replication and hot standby

=item *
    
Uses coroutines and asynchronous I/O to implement
high-performance lock-free access to data

=item *
    
Available on Linux, FreeBSD, Mac OS X

=item *
    
Stored procedures in Lua are supported.

=back

=head2 Data model

The basic atom of storage in Tarantool is called tuple. A tuple
can have arbitrary number of fields. The first field or fields 
in the tuple
are always the identifying unique key. Tuples form spaces. It is
possible to search tuples in spaces using the primary or secondary
keys. It is possible to change, as well as add or remove fields.

=head1 Command-line options

=over

=item -h, --help

Displays helpscreen and exits.

=item -V, --version

Prints program version and exits.

=back

