# encoding: utf-8
admin("i = 1 while true do box.insert(0, box.space[0]:len(), string.rep('test', i)) i = i + 1 end")
admin("box.space[0]:len()")
admin("i = 1 while true do box.insert(0, box.space[0]:len(), string.rep('test', i)) i = i + 1 end")
admin("box.space[0]:len()")
admin("i = 1 while true do box.insert(0, box.space[0]:len(), string.rep('test', i)) i = i + 1 end")
admin("box.space[0]:len()")
admin("box.space[0]:select(0, 0)")
admin("box.space[0]:select(0, 5)")
admin("box.space[0]:select(0, 9)")
admin("box.space[0]:select(0, 11)")
admin("box.space[0]:select(0, 15)")
# check that iterators work
admin("i = 0 for k,v in box.space[0]:pairs() do print(v) i = i + 1 if i == 50 then break end end")
admin("box.space[0]:truncate()")
admin("box.space[0]:insert(0, 'test')")
admin("box.space[0]:truncate()")
