box.execute("CREATE TABLE supersecret(id INT PRIMARY KEY, data TEXT);")
box.execute("CREATE TABLE supersecret2(id INT PRIMARY KEY, data TEXT);")
box.execute("INSERT INTO supersecret VALUES(1, 'very very big secret');")
box.execute("INSERT INTO supersecret2 VALUES(1, 'very big secret 2');")
box.execute("CREATE VIEW leak AS SELECT * FROM supersecret, supersecret2;")
box.schema.user.grant('guest', 'execute', 'sql')
remote = require 'net.box'
cn = remote.connect(box.cfg.listen)
cn:execute([[SET SESSION "sql_seq_scan" = true;]])

box.schema.user.grant('guest','read', 'space', 'leak')
cn:execute('SELECT * FROM leak;')
box.schema.user.grant('guest','read', 'space', 'supersecret')
cn:execute('SELECT * FROM leak;')

box.schema.user.revoke('guest','read', 'space', 'supersecret')
box.schema.user.revoke('guest','read', 'space', 'leak')
box.schema.user.revoke('guest', 'execute', 'sql')
box.execute("DROP VIEW leak;")
box.execute("DROP TABLE supersecret")
box.execute("DROP TABLE supersecret2")
