credentials:
  users:
    guest:
      roles: [ super ]

replication:
  failover: manual

groups:
  group-001:
    replicasets:
      replicaset-001:
        leader: instance-001
        instances:
          instance-001:
            iproto:
              listen:
                - uri: instance-001:3301
          instance-002:
            iproto:
              listen:
                - uri: instance-002:3302
          instance-003:
            iproto:
              listen:
                - uri: instance-003:3303
