=head1 NAME

tarantar - tarantool xlog compression utility.

=head1 SINOPSYS

Usage: C<< tarantar <options> <tarantool_config> >>

=head2 OPTIONS

=over

=item -c, --create

create snapshot file

=item -i, --interval <sec>

periodically create snapshot


=item -n, --lsn <u64>

snapshot lsn (latest by default)

=item -l, --limit <limit>

memory limit (bytes)

=item -help

display the helpscreen and exit

=item -v, --version

display version information and exit

=back
