=head1 NAME

tarantool_logrotate - utility to rotate tarantool instances logs


=head1 SINOPSYS

    tarantool_logrotate


=head1 DESCRIPTION

The utility tries to connect to each running tarantool instance to get
logger pid file, then it sends SIGUSR2 to logger which initiates
log rotataion procedure.
