=head1 NAME

tarantool_instance - utility to start/stop tarantool instances


=head1 SINOPSYS

    tarantool_instance NAME start
    tarantool_instance NAME stop


=head1 DESCRIPTION

The utility seeks instance in B</etc/tarantool/instances.enabled/> directory.
It seeks I<< /etc/tarantool/instances.enabled/B<NAME>.cfg >>, but You can use
filepath instead B<NAME>.

The utility extends tarantool's configs by the following variables:

=over

=item file_descriptors = COUNT

You can set sockets limit for the instance.

=back

The utility copies instance's config to directory
B</var/lib/tarantool/started/>, exclude additional variables,
then starts or stops instance.

In the first starting the utilitie creates
I<< /var/lib/tarantool/snapshot/B<NAME> >> directory and empty snapshot
inside the directory.
