import os

import pytest

import utils


@pytest.fixture(scope="session")
def tarantool_bin():
    default = "tarantool"
    return os.getenv("TARANTOOL_BIN", default)


@pytest.fixture(scope="session")
def tarantool_gdb_ext():
    return os.path.join(os.path.dirname(__file__), "..", "..", "tools", "tarantool-gdb.py")


@pytest.fixture(scope="session")
def tarantool_gdb(tarantool_bin, tarantool_gdb_ext):
    return utils.GdbSession("gdb", tarantool_bin, tarantool_gdb_ext)


# This fixture is a path to coredump generated by crashing tarantool. It is
# expected that tests are launched with non-root user and generally there is no
# guarantee that the user is able to remove the generated coredump, so this
# fixture is disabled by default and should be enabled explicitly as follows:
# ENABLE_COREDUMP_TESTS=1 python3 -m pytest test/gdb.
@pytest.fixture(scope="session")
def tarantool_coredump(tarantool_bin, tmpdir_factory):
    if os.getenv("ENABLE_COREDUMP_TESTS") is None:
        pytest.skip("coredump tests are disabled, use ENABLE_COREDUMP_TESTS=1 to enable them")
    cmd = [tarantool_bin, "-e", "require('ffi').cast('char *', 0)[0] = 42"]
    return utils.generate_coredump(cmd, tmpdir_factory.mktemp("coredump"))
