name: 'Pack and Deploy'
description: 'Pack and deploy the package'
runs:
  using: "composite"
  steps:
    - run: |
        # Our testing expects that the init process (PID 1) will
        # reap orphan processes. At least the following test leans
        # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
        export PACKPACK_EXTRA_DOCKER_RUN_PARAMS='--init'

        # Create packages.
        make -f .pack.mk package

        # Deploy live packages. Enabled only for 1.10 branch.
        if ${{ github.ref == 'refs/heads/1.10' }}; then
          REPO_TYPE=live make -f .pack.mk deploy
        fi

        # Deploy pre-release (since 2.10) and release packages. It's expected
        # that no one will push tags are used for pre-releases and releases.
        if ${{ ( startsWith(github.ref, 'refs/tags/1.10.') ||
                 startsWith(github.ref, 'refs/tags/2.') ) &&
               !endsWith(github.ref, '-entrypoint') }}; then
          case ${{ github.ref }} in
            # It's relevant since 2.10 only.
            refs/tags/*-alpha*|refs/tags/*-beta*|refs/tags/*-rc*)
              REPO_TYPE=pre-release make -f .pack.mk deploy
              ;;

            refs/tags/*)
              REPO_TYPE=release make -f .pack.mk deploy
              ;;
          esac
        fi
      shell: bash
