#!/bin/sh
INDENT=$(which gindent 2>/dev/null || which indent 2>/dev/null)
[ -z $INDENT ] && echo indent binary not found && exit 1
PARAM="-npro -kr -i8 -ts8 -sob -l100 -ss -ncs -cp1"
$INDENT $PARAM $@
