name: Install Deps OSX

description: Install build and test dependencies on OSX systems

runs:
  using: composite
  steps:
    - run: |
        brew install --force \
          openssl \
          readline \
          curl \
          icu4c \
          libiconv \
          zlib \
          cmake \
          ninja \
          autoconf \
          automake \
          libtool
      shell: bash
