#
# Build the bundled mimalloc allocator.
#
# mimalloc is linked into the tarantool executable as a single object file in
# its own malloc-override mode (MI_OVERRIDE): the object defines malloc/free/...
# and the mangled C++ operator new/delete, so the definitions in the executable
# take precedence over the libc and libstdc++ ones for the whole process,
# including the calls from shared libraries.
#
set(MIMALLOC_VERSION 3.5.1)
set(MIMALLOC_HASH 2602daad9b64b213a8835dee6fadda96d2081c0171bfcd3fb2db39bdc669d6b3)
set(MIMALLOC_INSTALL_DIR ${BUNDLED_LIBS_INSTALL_DIR}/mimalloc-prefix)
set(MIMALLOC_INCLUDE_DIR ${MIMALLOC_INSTALL_DIR}/include)

# mimalloc appends the build type to the library name unless it is a
# release-like one (mimalloc-debug, mimalloc-relwithdebinfo, ...).
# Mirror the logic to know the installed object file name.
string(TOLOWER "${CMAKE_BUILD_TYPE}" MIMALLOC_BUILD_TYPE_LC)
if(MIMALLOC_BUILD_TYPE_LC MATCHES "^(release|relwithdebinfo|minsizerel|none)$")
    set(MIMALLOC_LIBNAME mimalloc)
else()
    set(MIMALLOC_LIBNAME mimalloc-${MIMALLOC_BUILD_TYPE_LC})
endif()

# The object is generated by the external project at build time. Targets willing
# to link it must mark it with the EXTERNAL_OBJECT and GENERATED source file
# properties in their own directory, see src/CMakeLists.txt.
set(MIMALLOC_OBJECT ${MIMALLOC_INSTALL_DIR}/lib/${MIMALLOC_LIBNAME}.o)

set(MIMALLOC_CMAKE_ARGS
    "-DCMAKE_INSTALL_PREFIX=${MIMALLOC_INSTALL_DIR}"
    "-DCMAKE_INSTALL_LIBDIR=lib"
    "-DCMAKE_INSTALL_INCLUDEDIR=include"
    "-DMI_INSTALL_TOPLEVEL=ON"
    "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
    "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
    "-DCMAKE_LINKER=${CMAKE_LINKER}"
    "-DCMAKE_AR=${CMAKE_AR}"
    "-DCMAKE_RANLIB=${CMAKE_RANLIB}"
    "-DCMAKE_NM=${CMAKE_NM}"
    "-DCMAKE_STRIP=${CMAKE_STRIP}"
    # MI_STAT=1 makes mimalloc maintain the live allocation counters
    # (malloc_normal/malloc_huge), which are reported by `box.malloc.info()'.
    "-DCMAKE_C_FLAGS=${DEPENDENCY_CFLAGS} -DMI_STAT=1"
    # In hardened mode, which enables -fPIE by default, the cmake checks don't
    # work without -fPIC.
    "-DCMAKE_REQUIRED_FLAGS=-fPIC"
    "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    "-DMI_OVERRIDE=ON"
    "-DMI_BUILD_SHARED=OFF"
    "-DMI_BUILD_STATIC=ON"
    "-DMI_BUILD_OBJECT=ON"
    "-DMI_BUILD_TESTS=OFF"
)

ExternalProject_Add(bundled-mimalloc-project
    PREFIX ${MIMALLOC_INSTALL_DIR}
    SOURCE_DIR ${MIMALLOC_INSTALL_DIR}/src/mimalloc
    BINARY_DIR ${MIMALLOC_INSTALL_DIR}/src/mimalloc-build
    STAMP_DIR ${MIMALLOC_INSTALL_DIR}/src/mimalloc-stamp
    # TODO: Change to ${BACKUP_STORAGE}
    URL https://github.com/microsoft/mimalloc/archive/refs/tags/v${MIMALLOC_VERSION}.tar.gz
    URL_HASH SHA256=${MIMALLOC_HASH}
    CMAKE_ARGS ${MIMALLOC_CMAKE_ARGS}
    BUILD_BYPRODUCTS ${MIMALLOC_OBJECT}
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)

add_custom_target(bundled-mimalloc DEPENDS bundled-mimalloc-project)

message(STATUS "Using bundled mimalloc ${MIMALLOC_VERSION}")
