# find Termcap includes and library
#
# TERMCAP_FOUND
# TERMCAP_LIBRARY
# TERMCAP_INCLUDE_DIR

FIND_LIBRARY(TERMCAP_LIBRARY NAMES termcap)
FIND_PATH(TERMCAP_INCLUDE_DIR NAMES termcap.h)
SET (TERMCAP_FOUND FALSE)

IF (TERMCAP_LIBRARY)
	SET (TERMCAP_FOUND TRUE)
	MESSAGE(STATUS "Found Termcap: ${TERMCAP_LIBRARY}")
ENDIF ()

MARK_AS_ADVANCED(
	TERMCAP_FOUND
	TERMCAP_LIBRARY
	TERMCAP_INCLUDE_DIR
	)
