find_package(PkgConfig REQUIRED)

pkg_check_modules(SYSTEMD "systemd")

if (SYSTEMD_FOUND AND NOT SYSTEMD_SERVICES_INSTALL_DIR)
    execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=systemdsystemunitdir systemd OUTPUT_VARIABLE SYSTEMD_SERVICES_INSTALL_DIR)
    string(REGEX REPLACE "[ \t\n]+" "" SYSTEMD_SERVICES_INSTALL_DIR "${SYSTEMD_SERVICES_INSTALL_DIR}")
endif(SYSTEMD_FOUND AND NOT SYSTEMD_SERVICES_INSTALL_DIR)

if (NOT SYSTEMD_FOUND AND SYSTEMD_SERVICES_INSTALL_DIR)
    message (FATAL_ERROR "Variable SYSTEMD_SERVICES_INSTALL_DIR is defined,")
    message (FATAL_ERROR "but we can't find systemd using pkg-config")
endif(NOT SYSTEMD_FOUND AND SYSTEMD_SERVICES_INSTALL_DIR)

if (SYSTEMD_FOUND)
    message(STATUS "SYSTEMD_SERVICES_INSTALL_DIR: ${SYSTEMD_SERVICES_INSTALL_DIR}")
endif (SYSTEMD_FOUND)
