name: fedora_34

on:
  push:
    branches:
      - 'master'
      - 'release/**'
    tags:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch (1.10,
  # 2.8, etc.), and tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/heads/release/') ||
    startsWith(github.ref, 'refs/heads/2.') ||
    startsWith(github.ref, 'refs/heads/3.') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  fedora_34:
    # Run on push to the 'master' and release branches of tarantool/tarantool
    # or on pull request if the 'full-ci' label is set.
    if: github.repository == 'tarantool/tarantool' &&
        ( github.event_name != 'pull_request' ||
          contains(github.event.pull_request.labels.*.name, 'full-ci') )

    runs-on: ubuntu-20.04-self-hosted

    strategy:
      fail-fast: false
      matrix:
        build-type: [ '', 'gc64' ]

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/environment
      - name: packaging
        env:
          RWS_AUTH: ${{ secrets.RWS_AUTH }}
          OS: 'fedora'
          DIST: '34'
          GC64: ${{ matrix.build-type == 'gc64' }}
        uses: ./.github/actions/pack-and-deploy
      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: fedora-34${{ matrix.build-type == 'gc64' && '-gc64' || '' }}
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
      - name: Upload artifacts to S3
        uses: ./.github/actions/s3-upload-artifact
        if: ( success() || failure() ) && ( github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/2.') ||
          startsWith(github.ref, 'refs/heads/3.') ||
          startsWith(github.ref, 'refs/tags/') )
        with:
          job-name: ${{ github.job }} (${{ join(matrix.*, ', ') }})
          access-key-id: ${{ secrets.MULTIVAC_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.MULTIVAC_S3_SECRET_ACCESS_KEY }}
          source: ${{ env.VARDIR }}/artifacts
