name: freebsd

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  freebsd:
    # Run for tarantool/tarantool repository only.
    if: github.repository == 'tarantool/tarantool'

    runs-on: freebsd-${{ matrix.freebsd-version }}-mcs

    strategy:
      fail-fast: false
      matrix:
        freebsd-version: [ 12, 13 ]
        tarantool-branch:
          - 'master'
          - 'release/3.0'
          - 'release/2.11'
          - 'release/2.10'

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@master

      - name: Sources checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ matrix.tarantool-branch }}
          fetch-depth: 0
          submodules: recursive

      - uses: ./.github/actions/environment

      - name: Install deps
        uses: ./.github/actions/install-deps-freebsd

      - name: Run testing
        run: gmake -f .test.mk test-freebsd-release

      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: freebsd-${{ matrix.freebsd-version }}-${{ matrix.tarantool-branch }}
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts

      - name: Upload artifacts to S3
        uses: ./.github/actions/s3-upload-artifact
        if: ( success() || failure() ) && ( github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/') ||
          startsWith(github.ref, 'refs/tags/') )
        with:
          job-name: ${{ github.job }}
          access-key-id: ${{ secrets.MULTIVAC_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.MULTIVAC_S3_SECRET_ACCESS_KEY }}
          source: ${{ env.VARDIR }}/artifacts
