name: fuzzing

on:
  push:
    branches:
      - 'master'
      - '**-full-ci'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'test/fuzz/**'
      - 'test/static/corpus/**'

jobs:
  fuzzing:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]

    steps:
      - name: build fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'tarantool'
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
      - name: run fuzzers (${{ matrix.sanitizer }})
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'tarantool'
          fuzz-seconds: 600
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
      - name: upload crash
        uses: actions/upload-artifact@v1
        if: failure() && steps.build.outcome == 'success'
        with:
          name: ${{ matrix.sanitizer }}-artifacts
          retention-days: 21
          path: ./out/artifacts
