name: osx_release

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
    tags:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch (1.10,
  # 2.8, etc.), and tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    github.ref == 'refs/heads/1.10' ||
    startsWith(github.ref, 'refs/heads/2.') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  osx_release:
    # Run on push to the 'master' and release branches of tarantool/tarantool
    # or on pull request if the 'full-ci' label is set.
    if: github.repository == 'tarantool/tarantool' &&
        ( github.event_name != 'pull_request' ||
          contains(github.event.pull_request.labels.*.name, 'full-ci') )

    runs-on: [ 'macos-${{ matrix.version }}-self-hosted', '${{ matrix.arch }}' ]

    strategy:
      fail-fast: false
      matrix:
        version: [ 12, 13 ]
        arch: [ x86_64 ]

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/environment
      - name: Install deps
        uses: ./.github/actions/install-deps-osx
      - name: test
        env:
          SUFFIX: ${{ matrix.arch == 'aarch64' && '-arm64' || '' }}
        run: make -f .test.mk test-osx-release${SUFFIX}
      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: osx-${{ matrix.version }}-release-${{ matrix.arch }}
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
