name: ubuntu_22_04_aarch64

on:
  push:
    branches:
      - 'master'
      - 'release/**'
    tags:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow
  # run for this branch. However, the 'master' branch, release branch, and
  # tag workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow run ID' +
  # 'workflow run attempt' because it is a unique combination for any run.
  # So it effectively discards grouping.
  #
  # Important: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/heads/release/') ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  ubuntu_22_04_aarch64:
    # Run on push to the 'master' and release branches of tarantool/tarantool
    # or on pull request if the 'full-ci' label is set.
    if: github.repository == 'tarantool/tarantool' &&
        ( github.event_name != 'pull_request' ||
          contains(github.event.pull_request.labels.*.name, 'full-ci') )

    runs-on: graviton

    timeout-minutes: 60

    steps:
      - name: Prepare checkout
        uses: tarantool/actions/prepare-checkout@master
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/environment
      - name: packaging
        env:
          RWS_AUTH: ${{ secrets.RWS_AUTH }}
          OS: 'ubuntu'
          DIST: 'jammy'
          # We're using LXD containers as aarch64 runners. For some reason, OOM
          # killer just kills the compilation process when `make -j $(nproc)`.
          # The issue happens only with builds where LTO is enabled. It's found,
          # that `-j6` works fine. The bigger value causes problems.
          SMPFLAGS: '-j6'
        uses: ./.github/actions/pack-and-deploy
      - name: Send VK Teams message on failure
        if: failure()
        uses: ./.github/actions/report-job-status
        with:
          bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ubuntu-jammy
          retention-days: 21
          path: ${{ env.VARDIR }}/artifacts
      - name: Upload artifacts to S3
        uses: ./.github/actions/s3-upload-artifact
        if: ( success() || failure() ) && ( github.ref == 'refs/heads/master' ||
          startsWith(github.ref, 'refs/heads/release/') ||
          startsWith(github.ref, 'refs/tags/') )
        with:
          job-name: ${{ github.job }}
          access-key-id: ${{ secrets.MULTIVAC_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.MULTIVAC_S3_SECRET_ACCESS_KEY }}
          source: ${{ env.VARDIR }}/artifacts
